### ISSUE TITLE
Migrate Ohara document

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara-docs#22]
required by oharastream/ohara#5099

Items

- [x] User Guide(#30)
- [x] Custom Connector Guideline(#31 )
- [x] Custom Stream Guideline(#32)
- [x] Shabondi(#29)
- [x] Setting Definition Guide(#29)
- [x] How to build(#23)
- [x] Ohara Manager Development Guideline (@konekoya)(#24)
- [x] Docker and Docker-compose(#26)
- [x] Integration Test(#26)
- [x] Contributing(#23)
- [x] Ohara REST Interface
- [x] Fix broken links
- [x] test cases

**Comment by vitojeng** [comment]
@oharastream/developer 
It's time to start to ohara docs migration

**Comment by chia7712** [comment]
我已經等不及來給ohara瘦身了

**Comment by vitojeng** [comment]
是指 repo 的瘦身嗎?

**Comment by chia7712** [comment]
> 是指 repo 的瘦身嗎?

還有docker image的瘦身，把docs編譯的相關元件都砍掉

**Comment by vitojeng** [comment]
Migrate **testcase** document
